src/Plug.vala
=> Show GTK version

src/Plug.vala
=> Show kernel version

README.md, src/Plug.vala
This incorporates the changes from the OEM branch without the OEM parts
=> Split hardware and software into two columns

src/Plug.vala
=> Implement OEM support

src/CMakeLists.txt, src/Plug.vala, src/Views/HardwareView.vala
I'd like to break up this big class into a couple more manageable classes. After this is merged I'll do a software view also
=> Split hardware out into its own file

src/Views/HardwareView.vala
=> Use core count from /proc/cpuinfo if available

src/Views/HardwareView.vala
Improvements based upon feedback from @donadigo
=> Improve core count code

src/Plug.vala
=> Using null instead of a string with null

src/Views/HardwareView.vala
Steal the laptop detect code from switchboard-plug-power
=> Use laptop icon if we're on a laptop

src/Views/HardwareView.vala
Fixes #53 ... I think. Someone with multiple graphics cards needs to test
=> Set center justify on graphics label

src/Dialogs/IssueDialog.vala
because #57 won't be solved right now
=> Avoid waste of localization effort, better memory management

src/Dialogs/IssueDialog.vala
=> Add network indicator to report a problem

src/Plug.vala
This handles things like media keys, orientation lock, night light, housekeeping, power, etc
=> Add SettingsDaemon to key resets

src/Plug.vala
Support LOGO field in os-release
Introduced recently in systemd https://github.com/systemd/systemd/commit/e7f7f19abccc25449e321b816b8f9419a5a3ec2b
=> Support LOGO field in os-release

data/io.elementary.switchboard.about.appdata.xml.in, data/meson.build
=> Rename Appdata to use the right RDNN

src/Dialogs/IssueDialog.vala
This pull request aims to resolve https://github.com/elementary/switchboard-plug-about/issues/85.
=> Added support for Epiphany in Report a Problem

src/Plug.vala
For https://github.com/elementary/onboarding/pull/16
=> Add Onboarding settings to reset

src/Plug.vala
=> Check if os-release icon is null

src/Plug.vala
=> Plug: Use pretty name when available

debian/control
=> Debian control: Add libgtop2 dependency

src/Plug.vala
See: https://github.com/elementary/feedback/issues/31
=> Plug: “Report a Problem” → “Send Feedback”

src/Plug.vala
=> Plug: Update search term

README.md, data/io.elementary.switchboard.about.appdata.xml.in, src/Plug.vala
Fixes #124, at least in user-facing strings
=> Rename user-facing strings to System

src/Plug.vala
=> Fix plug destroyed on navigation

data/io.elementary.switchboard.about.appdata.xml.in, src/Plug.vala
Closes https://github.com/elementary/switchboard-plug-about/issues/147
=> Change icon to the cute CPU looking one

po/POTFILES, src/Plug.vala, src/Views/OperatingSystemView.vala, src/meson.build
So that #150 is purely about adding a firmware view and also doesn't include this refactor
=> Split Hardware and OS views into tabs

src/Views/OperatingSystemView.vala
=> OperatingSystemView: Better align links

src/Views/HardwareView.vala, src/Views/OperatingSystemView.vala
Because @katiemkblaede is smart
=> Moar whitespace

src/Interfaces/FwupdManager.vala
This is a PR into an already open PR...
@meisenzahl I've opened this as a PR because it would have been quite complicated to explain in a code review :sweat_smile: 
Can you test this still works (I don't have any devices that support fwupd) ?
If so, you should be able to do the same for pretty much all your DBus methods and the code will be a lot cleaner. Ping me on Slack if you need any help!
=> FwupdManager: Refactor get_devices

src/Plug.vala
Fixes #178 and cleans it up to work with the stack switcher
=> Plug: Add and clean up search strings

src/Views/FirmwareReleaseView.vala
Some layout tweaks, including adding a scrolled window to ensure things don't grow out of hand.
=> FirmwareReleaseView: Layout tweaks

src/Views/HardwareView.vala
Don't block the constructor (and hence the plug loading) by using synchronous DBus calls.
=> HardwareView: Get GPU info asynchronously

src/Views/HardwareView.vala
This should be about it for asyncifying most things here now. Loading the plug definitely feels snappier after all these PRs. I've tested that OEM logos still work here too.
=> HardwareView: Connect to systemd-hostnamed asynchronously

src/Views/HardwareView.vala
Get rid of all this blocking I/O in the constructor
=> HardwareView: Asyncify storage methods

src/Interfaces/FwupdManager.vala
Closes https://github.com/elementary/switchboard-plug-about/issues/200
=> Provide fallback icon for firmware devices

src/Config.vala.in, src/Views/FirmwareView.vala, src/meson.build
ngettext is using the domain from textdomain() which is specified by switchboard itself
=> Use dngettext instead of ngettext

debian/control
Needed for https://github.com/elementary/switchboard-plug-about/pull/182
=> Control: Add libappstream dep

data/io.elementary.switchboard.about.appdata.xml.in, meson.build
Big ones I'm interested in for StarBook:
- https://github.com/elementary/switchboard-plug-about/pull/244
- https://github.com/elementary/switchboard-plug-about/pull/209
Waiting a bit for translations, but this is blocking the StarBook launch.
=> Release 6.1.0

meson.build, src/Views/HardwareView.vala, src/meson.build
It is required as we _only_ have 2.72 in Jammy
=> HardwareView: Support GLib < 2.73 translation

src/Views/FirmwareView.vala, src/Views/OperatingSystemView.vala
GTK 4 prep. No dialog.run () in GTK 4 so make sure we connect to response signal instead
=> dialog.run () → dialogresponse.connect ()

meson.build, src/Views/FirmwareReleaseView.vala, src/meson.build
=> Add support for AppStream 1.0

debian/changelog, debian/control, debian/rules
=> Re-namespace for GTK 4

src/Views/OperatingSystemView.vala
Goes with https://github.com/elementary/settings-daemon/pull/118
=> OperatingSystemView: Add a switch for automatic updates

src/Views/OperatingSystemView.vala
* Makes the whole auto updates row clickable
* Automatically styles separator, frame, etc
=> OperatingSystemView: use boxed-list, modelbutton

src/Views/HardwareView.vala
* Add a save icon to the entry when its text is different from the current host name
* Add a spinner while we're setting the new hostname
* Add a checkmark icon when the new host name is saved
=> Add feedback to host name entry

src/Plug.vala
Make sure this is updated for all the latest features/links/etc
=> Plug: add more search terms

src/Views/OperatingSystemView.vala
=> Add hexpand

src/Views/OperatingSystemView.vala
=> Fix Scroll Padding

src/Plug.vala
To make sure the headerbar has a shadow when we scroll
=> Plug: use Adw.ToolbarView

src/DBus/SystemUpdate.vala, src/Views/OperatingSystemView.vala
Goes hand-in-hand with https://github.com/elementary/settings-daemon/pull/179
=> Show update size in OperatingSystemView

data/system.metainfo.xml.in, src/Plug.vala
=> Plug: add about this device search result
