src/Plug.vala

Fixes #31 
This PR specifies an pixel_size for the OS Logo Icon, which ensures that it's displayed at the right size even if an icon theme without 128px icons is used. The icon size matches the size that is originally requested, so there shouldn't be any conflicts with the elementary theme.

Specify an icon pixel size for the OS Logo Icon

---

src/Plug.vala

In case of some ridiculous long name like "Ubuntu Artful Aardvark (Development Branch)"

Plug.vala: ellipsize long distro names

---

src/Plug.vala
src/RestoreDialog.vala

* `margin_right` and `margin_left` have been replaced by `margin_end` and `margin_start`
* `Gtk.icon_size_register` is deprecated so just use `icon_name` on a separate line

Fix a few deprecation warnings

---

src/Plug.vala
src/Views/HardwareView.vala

* make sure that images are the same distance from separator
* added left margin to software and right margin to hardware so that grids are centered evenly between window edge and separator when you downsize window 
* use ellipsis on hardware labels so that window doesn't auto-resize if text is too big
* oem product was aligned on right if there was no oem version provided

Fix layout

---

src/Plug.vala

Don't remove the org.pantheon keys because Gala still uses that settings path

Add new RDNN keys to reset

---

src/Dialogs/IssueDialog.vala

Fixes https://github.com/elementary/switchboard-plug-display/issues/132
Fixes #73

Fix wrong GitHub URL for switchboard-plug-display

---

src/Views/HardwareView.vala

Fixes #63
Supersedes #67
I made this PR because it looks like the branch of that PR no longer exists :cry:
The original PR checks whether system storage is SSD or HDD, but this PR also recognizes whether it's NVMe, eMMC, or SATA.
* Show whether the system storage is NVMe SSD / eMMC / SATA SSD / HDD (#67 + α)

Show what kind of storage is used

---

src/Plug.vala

Alternative to #97 that checks for the existence of AppCenter before creating the update button

Plug: check for AppCenter before creating updates button

---

src/Views/HardwareView.vala

Fixes #106 
Supersedes #125 
This is @jhaygood86 's work from that original PR, I've just pushed an extra commit with some requested fixes after the PR went stale.
As an aside, this allows the about plug to correctly display the GPU in my Pinebook Pro where it previously displayed nothing.

Get GPU model from SessionManager

---

vapi/libgtop-2.0.vapi

GLib.GenericArray is the vala-binding version of GLib.PtrArray

libgtop-2.0: Replace GLib.PtrArray by GLib.GenericArray

---

src/Views/OperatingSystemView.vala

This was useful and made sense in a world with unstable GTK 3 API, but in a flatpak world where apps may be using their own GTK version this only tells us what version of GTK is being used by the about plug. So it's not terribly useful anymore

OSView: Remove GTK version

---

src/Views/HardwareView.vala

More breathing room for logos.

HardwareView: Use 24px of column spacing

---

po/POTFILES
src/Views/FirmwareView.vala

So that we can show the new firmware view in translated strings correctly

Update POTFILES and correct gettext syntax

---

src/Views/OperatingSystemView.vala

I noticed we weren't resetting these.

OperatingSystemView: Add Keyboard indicator settings to reset

---

src/Views/FirmwareView.vala
src/Widgets/FirmwareUpdateRow.vala

The port to libfwupd has introduced a regression related to the logic of whether a device is up to date.
In both cases, "Unifying Receiver" is at version RQR12.07_B0029 which is lower than the latest release RQR12.10_B0032.

Fix logic if device is up to date

---

.github/workflows/main.yml
README.md
po/POTFILES
src/Views/FirmwareReleaseView.vala
src/Views/FirmwareView.vala
src/Widgets/FirmwareUpdateRow.vala
src/meson.build

Supersedes https://github.com/elementary/switchboard-plug-about/pull/182
Closes https://github.com/elementary/switchboard-plug-about/issues/172

Add detail page for firmware releases - Revenge of libfwupd

---

src/Views/HardwareView.vala

- Use middle ellipsis in hardware names to make sure it's easy to distinguish the devices and also, in the case of audio devices, to be consistent with how the indicator displays them.
- Add margin to the left and right so long hardware names are properly displayed.
Before and after:

Handle long hardware names

---

src/Views/OperatingSystemView.vala

With the patch attached, the "(null)" string interpolation of missing OS version is removed from the operating system name label.
With that patch applied, the about window looks like this:
This fix #237

Avoid ugly (null) label on some rolling releases distributions

---

src/Interfaces/FirmwareClient.vala
src/Views/FirmwareView.vala

Closes #243
This should fix the problem. Unfortunately, I can not test this due to lack of hardware. @Sean-StarLabs can you test if this works?

Add support for offline firmware updates

---

src/Views/HardwareView.vala

Some fixups to handle specific Ryzen CPU and AMD GPU vendor strings in the regex replacement cleanup method.
Also, break after the first regex match, so the replacement strings are in order of preference now.
Before: (note the lowercasing of the cpu string and lengthy gpu string)
After: (note the generic gpu string part matched, instead of the "RX 570" trailer because the actual gpu is an RX 580)

Handle Ryzen CPU and AMD GPU vendor string and break on first regex match

---

.github/workflows/main.yml
README.md
src/Views/HardwareView.vala
src/meson.build

Stolen code from GNOME settings repo to use UDev and UDisks libraries to get more accurate memory and storage info.
Memory now shows the physical RAM capacity and storage code collects the total size of all non-removable and non-ejectable disks.
Before: (note the non-physical RAM size using glibtop.mem library and storage size of the root partition only)
After: (note the more accurate physical RAM size and storage size of the physical disk)

Better memory and storage info

---

src/Interfaces/LoginManager.vala
src/Views/FirmwareView.vala

* Return the error message from LoginManager so we can display it in the dialog details
* Simplify single-use functions
* Use `dialog.present ()`
* Set dialogs modal
* Use more descriptive error dialog copy

Simplify, show error message in dialog

---

src/Interfaces/LoginManager.vala
src/Views/FirmwareView.vala
src/Views/OperatingSystemView.vala

If I ever need to make changes on the firmware (BIOS/UEFI) of my device, I often don't know which key combination to press when starting the device to get there. Windows offers an option to boot directly into BIOS/UEFI. On Linux, I have used https://www.freedesktop.org/software/systemd/man/systemctl.html#--firmware-setup for this so far. This feature adds a button that reboots the device and starts the BIOS/UEFI.

Reboot to Firmware Setup

---

meson.build
meson_options.txt
src/Views/OperatingSystemView.vala

Actually the main motivation is `/usr/share` does not exist on NixOS so the wallpaper path won't work for us without patching :-(
Closes #235

Add meson option for overlaying logo on wallpaper

---

src/Views/HardwareView.vala

Allows to not have duplicates of the string already availables.

HardwareView: Reuse translations from GLib

---

src/Views/HardwareView.vala

* Bump copyright header
* Replace Grid with Box
* Code style

HardwareView: GTK 4 prep

---

src/Views/OperatingSystemView.vala

This was missing a few settings namespaces. While we're here use a more descriptive icon pair

OperatingSystemView: expand restore defaults coverage, change icons

---

po/POTFILES
src/Views/OperatingSystemView.vala
src/Widgets/UpdateDetailsDialog.vala
src/meson.build

Pretty basic atm, but does the thing

Add package details dialog

---

src/Plug.vala
src/Views/HardwareView.vala
src/Views/OperatingSystemView.vala

Clamp views instead of halign

---

.github/workflows/main.yml
README.md
src/DBus/SystemUpdate.vala
src/Views/OperatingSystemView.vala
src/meson.build

Fixes #291 
Depends on https://github.com/elementary/settings-daemon/pull/120

OperatingSystemView: use urgent icon if updates contain security

---

src/Plug.vala
src/Views/OperatingSystemView.vala

- Loads the wallpaper logo asynchronoulsy when the plug was shown
- Fixes a quite noticeable delay when clicking the plug until it's shown
- We begin loading only when the plug was actually shown because otherwise setting the paintable from data still makes the animation stutter
- Also fixes #272 by loading an empty paintable before replacing it

OperatingSystemView: load logo asynchronoulsy when the plug was shown

---

src/Views/OperatingSystemView.vala

Show a placeholder if no connection to the settings-daemon could be established

---

src/Views/FirmwareReleaseView.vala
src/Views/OperatingSystemView.vala
src/Widgets/UpdateDetailsDialog.vala
src/meson.build

Fixes #318
- Use dngettext instead of gettext
- Correct GETTEXT_PACKAGE value

l10n: Fix some strings not shown as translated

---

data/OperatingSystemView.css
src/Views/OperatingSystemView.vala
src/Widgets/FirmwareUpdateRow.vala

Only non-deprecated use of Gtk.StyleContext is to add a provider for display

Fix deprecated use of get_style_context ()

---

meson.build
src/Views/FirmwareReleaseView.vala
src/Views/FirmwareView.vala
src/meson.build

- Generally based on [Arch's patch](https://gitlab.archlinux.org/archlinux/packaging/packages/switchboard-plug-about/-/commit/d3716abb1a37b88a427a4227bdfb63dcf915f757).
- The `fwupd_release_get_locations` usage is also inspired by [KDE discover](https://invent.kde.org/plasma/discover/-/blob/v6.2.3/libdiscover/backends/FwupdBackend/FwupdBackend.cpp?ref_type=tags#L203) and [GNOME software](https://github.com/GNOME/gnome-software/blob/011d52b3c3388ca88421edeae8045f24b4f60c9d/plugins/fwupd/gs-plugin-fwupd.c#L542).
- Offline support is [gone](https://github.com/fwupd/fwupd/commit/ee40786de8800201e1676355c0709e947bd95474).

build: Fix build with fwupd 2.0.0

---

.github/workflows/main.yml
README.md
src/Views/OperatingSystemView.vala
src/meson.build

Use LibSoup for request instead of commandline curl (which may not be present).

Use Soup for request

---

src/Views/OperatingSystemView.vala
src/meson.build
vapi/monetary.vapi

Addresses https://github.com/elementary/switchboard-plug-about/pull/347#issuecomment-2524541907 and plus correct gettext format while I'm here.
en_US that uses `,` for delimiters:
de_DE that uses `.` for delimiters:

Only translate delimiters and not monetary symbols

---

src/Views/OperatingSystemView.vala

This improves UX, making elements in `software_grid` not change their position and therefore be predictable and "steady".

Prevent `software_grid` change vertical position, when content changes

---

src/DBus/SystemUpdate.vala
src/Views/OperatingSystemView.vala

Fixes #342
See also: https://github.com/elementary/settings-daemon/pull/175#issue-2760622522

SystemUpdate: Get last refresh time directly from Settings Daemon instead of via GSettings

---

src/Views/OperatingSystemView.vala

- Lessen scope
- Lessen coupling
- Rename the method to avoid confusion of the getter method
- Unify naming notation: "xxx_size_str" is stringfied data of "xxx_size"

OperatingSystemView: Suggested changes

---

debian/control

Depends on new API in the settings daemon to show updates download progress
Merge after: https://github.com/elementary/settings-daemon/pull/181

Control: bump runtime dep for settings daemon

---

src/Views/OperatingSystemView.vala

In other places like the Files file transfer dialog we use "of" instead of a "/"

OperatingSystemView.vala: use of in download progress string

---

src/Views/OperatingSystemView.vala

Related to https://github.com/elementary/switchboard/discussions/343
Make it more clear that this is instructional text and not just informational text. Explicitly communicate that updates have been downloaded. Also makes the text a little less redunant

OperatingSystemView: more explicit restart directions

---

src/Views/FirmwareReleaseView.vala
src/Views/FirmwareView.vala

* Replace deprecated Adw.Leaflet with Adw.NavigationView
* Use Adw.ToolbarView and Gtk.HeaderBar to avoid a bunch of custom styling

FirmwareView: use Adw.NavigationView
